encoding: utf-8

# SEO相关信息
title: ipsum-0320's Blog
description: ipsum-0320 的个人博客
keywords: ipsum-0320, Blog, Java, Python, Go, TypeScript, Kubernetes
author: ipsum-0320
footerText: 'Copyright © 2024'

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['README.md', '_site', 'dist', 'Gemfile', 'Gemfile.lock']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://ipsum-0320/github.io'
baseurl: ''

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 关于
    url: /pages/about.html

# Google Adsense，不需要请设置为 false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为 false
# 在具体的 post 中使用，需要在 yaml 中声明 extMath: true
extMath: true
